#%RAML 0.8

/countries:
  get: 
/countries/{zid}:
  get: 
/countries/{zid}/states/{sid}:
  get: 
/countries/{zid}/states/{sid}/cities/{cid}:
  get: 
/countries/{zid}/states:
  get: 
/countries/{zid}/states/{sid}/cities:
  get: 
/autocomplete/country/{str}:
  get: 
/autocomplete/state/{str}:
  get: 
/autocomplete/city/{str}:
  get: 
/locate/{longitude}/{latitude}:
  get: 